[build]
  command = "./build.sh"
  functions = "functions"
  publish = "src/public"

[build.environment]
  GO_IMPORT_PATH = "github.com/shop-green/backend"
  GO111MODULE = "on"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/backend/:splat"
  status = 200
